// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package main

// Defines values for Products.
const (
	ProductsProductA Products = "ProductA"
	ProductsProductB Products = "ProductB"
	ProductsProductC Products = "ProductC"
)

// Products defines model for products.
type Products string
