// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package main

// Defines values for Menus.
const (
	MenusMenusA Menus = "1"
	MenusMenusB Menus = "2"
	MenusMenusC Menus = "3"
)

// Valid indicates whether the value is a known member of the Menus enum.
func (e Menus) Valid() bool {
	switch e {
	case MenusMenusA:
		return true
	case MenusMenusB:
		return true
	case MenusMenusC:
		return true
	default:
		return false
	}
}

// Defines values for Products.
const (
	ProductsProductA Products = 1
	ProductsProductB Products = 2
	ProductsProductC Products = 3
)

// Valid indicates whether the value is a known member of the Products enum.
func (e Products) Valid() bool {
	switch e {
	case ProductsProductA:
		return true
	case ProductsProductB:
		return true
	case ProductsProductC:
		return true
	default:
		return false
	}
}

// ProductID defines model for ProductID.
type ProductID = int32

// UserID defines model for UserID.
type UserID = string

// Menus defines model for menus.
type Menus string

// Products defines model for products.
type Products int
