/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        products: {
            /** @enum {string} */
            ProductA?: ProductsProductA;
            /** @enum {string} */
            ProductB?: ProductsProductB;
            /** @enum {string} */
            ProductC?: ProductsProductC;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum ProductsProductA {
    Value1 = "1"
}
export enum ProductsProductB {
    Value2 = "2"
}
export enum ProductsProductC {
    Value3 = "3"
}
export type operations = Record<string, never>;
