package app

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/flum1025/sql-enum-generator/internal/entity"
)

func TestSchemaGenerator_Run(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		config string
		want   string
	}{
		{
			name:   "without id_type",
			config: "version: \"1\"\ntables:\n  - name: products\n    key: name\n    value: id\n  - name: menus\n    key: name\n    value: id\n",
			want:   `{"openapi":"3.0.0","info":{"title":"Code generated by github.com/flum1025/sql-enum-generator, DO NOT EDIT.","version":""},"paths":{},"components":{"schemas":{"menus":{"enum":["1","2","3"],"type":"string","x-enum-varnames":["MenusA","MenusB","MenusC"]},"products":{"enum":["1","2","3"],"type":"integer","x-enum-varnames":["ProductA","ProductB","ProductC"]}}}}`,
		},
		{
			name:   "with id_type",
			config: "version: \"1\"\ntables:\n  - name: products\n    key: name\n    value: id\n    id_type: ProductID\n  - name: menus\n    key: name\n    value: id\n",
			want:   `{"openapi":"3.0.0","info":{"title":"Code generated by github.com/flum1025/sql-enum-generator, DO NOT EDIT.","version":""},"paths":{},"components":{"schemas":{"menus":{"enum":["1","2","3"],"type":"string","x-enum-varnames":["MenusA","MenusB","MenusC"]},"products":{"enum":["1","2","3"],"type":"integer","x-enum-varnames":["ProductA","ProductB","ProductC"],"x-id-type":"ProductID"}}}}`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			dir := t.TempDir()
			configPath := filepath.Join(dir, "sqlenumgen.yml")
			outputPath := filepath.Join(dir, "openapi.generated.json")

			if err := os.WriteFile(configPath, []byte(tt.config), 0644); err != nil {
				t.Fatal(err)
			}

			a, err := NewSchemaGenerator(SchemaGeneratorOption{
				Engine:     entity.EnginePostgres,
				ConfigPath: configPath,
				SourcePath: "../../example/master.sql",
				OutputPath: outputPath,
			})
			if err != nil {
				t.Fatalf("NewSchemaGenerator() error = %v", err)
			}

			if err := a.Run(); err != nil {
				t.Fatalf("Run() error = %v", err)
			}

			got, err := os.ReadFile(outputPath)
			if err != nil {
				t.Fatal(err)
			}

			if !bytes.Equal(got, []byte(tt.want)) {
				t.Errorf("output =\n%s\nwant\n%s", got, tt.want)
			}
		})
	}
}
