package app

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/flum1025/sql-enum-generator/internal/entity"
)

func TestSchemaGenerator_Run_WithoutIDs(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	configPath := filepath.Join(dir, "sqlenumgen.yml")
	outputPath := filepath.Join(dir, "openapi.generated.json")

	config := "version: \"1\"\ntables:\n  - name: products\n    key: name\n    value: id\n  - name: menus\n    key: name\n    value: id\n"
	if err := os.WriteFile(configPath, []byte(config), 0644); err != nil {
		t.Fatal(err)
	}

	for _, schemaPath := range []string{"", "../../example/schema.sql"} {
		a, err := NewSchemaGenerator(SchemaGeneratorOption{
			Engine:     entity.EnginePostgres,
			ConfigPath: configPath,
			SourcePath: "../../example/master.sql",
			SchemaPath: schemaPath,
			OutputPath: outputPath,
		})
		if err != nil {
			t.Fatalf("NewSchemaGenerator() error = %v", err)
		}

		if err := a.Run(); err != nil {
			t.Fatalf("Run() error = %v", err)
		}

		got, err := os.ReadFile(outputPath)
		if err != nil {
			t.Fatal(err)
		}

		want := `{"openapi":"3.0.0","info":{"title":"Code generated by github.com/flum1025/sql-enum-generator, DO NOT EDIT.","version":""},"paths":{},"components":{"schemas":{"menus":{"enum":["1","2","3"],"type":"string","x-enum-varnames":["MenusA","MenusB","MenusC"]},"products":{"enum":["1","2","3"],"type":"integer","x-enum-varnames":["ProductA","ProductB","ProductC"]}}}}`
		if !bytes.Equal(got, []byte(want)) {
			t.Errorf("schemaPath=%q output =\n%s\nwant\n%s", schemaPath, got, want)
		}
	}
}

func TestNewSchemaGenerator_RequiresSchemaPathForIDs(t *testing.T) {
	t.Parallel()

	_, err := NewSchemaGenerator(SchemaGeneratorOption{
		Engine:     entity.EnginePostgres,
		ConfigPath: "../../example/sqlenumgen.yml",
		SourcePath: "../../example/master.sql",
		OutputPath: filepath.Join(t.TempDir(), "openapi.generated.json"),
	})
	if err == nil || !strings.Contains(err.Error(), "schema path is required when id_type is configured") {
		t.Fatalf("NewSchemaGenerator() error = %v", err)
	}
}

func TestSchemaGenerator_Run_Example(t *testing.T) {
	t.Parallel()

	want, err := os.ReadFile("../../example/openapi.generated.json")
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name       string
		schemaPath string
	}{
		{name: "sqldef", schemaPath: "../../example/schema.sql"},
		{name: "pg_dump", schemaPath: "testdata/schema.pg_dump.sql"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			outputPath := filepath.Join(t.TempDir(), "openapi.generated.json")

			a, err := NewSchemaGenerator(SchemaGeneratorOption{
				Engine:     entity.EnginePostgres,
				ConfigPath: "../../example/sqlenumgen.yml",
				SourcePath: "../../example/master.sql",
				SchemaPath: tt.schemaPath,
				OutputPath: outputPath,
			})
			if err != nil {
				t.Fatalf("NewSchemaGenerator() error = %v", err)
			}

			if err := a.Run(); err != nil {
				t.Fatalf("Run() error = %v", err)
			}

			got, err := os.ReadFile(outputPath)
			if err != nil {
				t.Fatal(err)
			}

			if !bytes.Equal(got, want) {
				t.Errorf("output =\n%s\nwant\n%s", got, want)
			}
		})
	}
}
