package writer

import (
	"fmt"
	"os"

	"github.com/flum1025/sql-enum-generator/internal/entity"
	"github.com/flum1025/sql-enum-generator/internal/parser"
	"github.com/samber/lo"
	"github.com/swaggest/openapi-go/openapi3"
)

var _ Writer = &OpenAPIWriter{}

type OpenAPIWriter struct {
	targetSchemaTables []entity.SchemaTable
	outputPath         string
}

func NewOpenAPIWriter(
	targetSchemaTables []entity.SchemaTable,
	outputPath string,
) *OpenAPIWriter {
	return &OpenAPIWriter{
		targetSchemaTables: targetSchemaTables,
		outputPath:         outputPath,
	}
}

func (w *OpenAPIWriter) Write(
	tables []parser.Table,
	ids []parser.ID,
) error {
	nameToTable := lo.SliceToMap(
		tables,
		func(table parser.Table) (string, parser.Table) {
			return table.Name, table
		},
	)

	tableToID := lo.SliceToMap(
		ids,
		func(id parser.ID) (string, parser.ID) {
			return id.Table, id
		},
	)

	spec := openapi3.Spec{
		Openapi: "3.0.0",
		Info: openapi3.Info{
			Title: "Code generated by github.com/flum1025/sql-enum-generator, DO NOT EDIT.",
		},
	}

	spec.Components = &openapi3.Components{
		Schemas: &openapi3.ComponentsSchemas{
			MapOfSchemaOrRefValues: lo.SliceToMap(
				w.targetSchemaTables,
				func(table entity.SchemaTable) (string, openapi3.SchemaOrRef) {
					def := nameToTable[table.Name]
					enumDef := def.Rows.ToEnum(table)

					schemaType := func() openapi3.SchemaType {
						switch enumDef.ValueType {
						case parser.RowTypeInteger:
							return openapi3.SchemaTypeInteger
						case parser.RowTypeString:
							return openapi3.SchemaTypeString
						default:
							return openapi3.SchemaTypeString
						}
					}()

					extensions := map[string]any{
						"x-enum-varnames": lo.ToAnySlice(enumDef.Keys),
					}

					if id, ok := tableToID[table.Name]; ok {
						extensions["x-id-type"] = id.Name
					}

					return enumDef.Name, openapi3.SchemaOrRef{
						Schema: &openapi3.Schema{
							Type:          lo.ToPtr(schemaType),
							Enum:          lo.ToAnySlice(enumDef.Values),
							MapOfAnything: extensions,
						},
					}
				},
			),
		},
	}

	for _, id := range ids {
		if _, ok := spec.Components.Schemas.MapOfSchemaOrRefValues[id.Name]; ok {
			return fmt.Errorf("duplicate schema name: %s", id.Name)
		}

		schemaType, format := idSchemaType(id.Type)

		spec.Components.Schemas.MapOfSchemaOrRefValues[id.Name] = openapi3.SchemaOrRef{
			Schema: &openapi3.Schema{
				Type:   lo.ToPtr(schemaType),
				Format: lo.ToPtr(format),
				MapOfAnything: map[string]any{
					"x-id": true,
				},
			},
		}
	}

	bytes, err := spec.MarshalJSON()
	if err != nil {
		return fmt.Errorf("marshal bytes: %w", err)
	}

	if err := os.WriteFile(w.outputPath, bytes, 0644); err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	return nil
}

func idSchemaType(idType parser.IDType) (openapi3.SchemaType, string) {
	switch idType {
	case parser.IDTypeInt32:
		return openapi3.SchemaTypeInteger, "int32"
	case parser.IDTypeInt64:
		return openapi3.SchemaTypeInteger, "int64"
	default:
		return openapi3.SchemaTypeString, "uuid"
	}
}
