package writer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/flum1025/sql-enum-generator/internal/entity"
	"github.com/flum1025/sql-enum-generator/internal/parser"
)

func TestOpenAPIWriter_Write(t *testing.T) {
	t.Parallel()

	targetSchemaTables := []entity.SchemaTable{
		{Name: "products", Key: "name", Value: "id"},
		{Name: "menus", Key: "name", Value: "id"},
	}

	tables := []parser.Table{
		{
			Name: "products",
			Rows: parser.Rows{
				{{Name: "id", Value: "1", Type: parser.RowTypeInteger}, {Name: "name", Value: "ProductA", Type: parser.RowTypeString}},
				{{Name: "id", Value: "2", Type: parser.RowTypeInteger}, {Name: "name", Value: "ProductB", Type: parser.RowTypeString}},
			},
		},
		{
			Name: "menus",
			Rows: parser.Rows{
				{{Name: "id", Value: "1", Type: parser.RowTypeString}, {Name: "name", Value: "MenusA", Type: parser.RowTypeString}},
			},
		},
	}

	tests := []struct {
		name    string
		ids     []parser.ID
		want    string
		wantErr string
	}{
		{
			name: "without ids",
			ids:  nil,
			want: `{"openapi":"3.0.0","info":{"title":"Code generated by github.com/flum1025/sql-enum-generator, DO NOT EDIT.","version":""},"paths":{},"components":{"schemas":{"menus":{"enum":["1"],"type":"string","x-enum-varnames":["MenusA"]},"products":{"enum":["1","2"],"type":"integer","x-enum-varnames":["ProductA","ProductB"]}}}}`,
		},
		{
			name: "with ids",
			ids: []parser.ID{
				{Name: "ProductID", Table: "products", Type: parser.IDTypeInt32},
				{Name: "EventID", Table: "events", Type: parser.IDTypeInt64},
				{Name: "UserID", Table: "users", Type: parser.IDTypeUUID},
			},
			want: `{"openapi":"3.0.0","info":{"title":"Code generated by github.com/flum1025/sql-enum-generator, DO NOT EDIT.","version":""},"paths":{},"components":{"schemas":{"EventID":{"type":"integer","format":"int64","x-id":true},"ProductID":{"type":"integer","format":"int32","x-id":true},"UserID":{"type":"string","format":"uuid","x-id":true},"menus":{"enum":["1"],"type":"string","x-enum-varnames":["MenusA"]},"products":{"enum":["1","2"],"type":"integer","x-enum-varnames":["ProductA","ProductB"],"x-id-type":"ProductID"}}}}`,
		},
		{
			name: "duplicate schema name",
			ids: []parser.ID{
				{Name: "menus", Table: "menus", Type: parser.IDTypeInt32},
			},
			wantErr: "duplicate schema name: menus",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			outputPath := filepath.Join(t.TempDir(), "openapi.generated.json")

			err := NewOpenAPIWriter(targetSchemaTables, outputPath).Write(tables, tt.ids)
			if tt.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("Write() error = %v, want %q", err, tt.wantErr)
				}

				return
			}

			if err != nil {
				t.Fatalf("Write() error = %v", err)
			}

			got, err := os.ReadFile(outputPath)
			if err != nil {
				t.Fatalf("read output: %v", err)
			}

			if string(got) != tt.want {
				t.Errorf("Write() output =\n%s\nwant\n%s", got, tt.want)
			}
		})
	}
}
