package writer

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/flum1025/sql-enum-generator/internal/entity"
	"github.com/flum1025/sql-enum-generator/internal/parser"
)

func TestOpenAPIWriter_Write(t *testing.T) {
	t.Parallel()

	tables := []parser.Table{
		{
			Name: "products",
			Rows: parser.Rows{
				{{Name: "id", Value: "1", Type: parser.RowTypeInteger}, {Name: "name", Value: "ProductA", Type: parser.RowTypeString}},
				{{Name: "id", Value: "2", Type: parser.RowTypeInteger}, {Name: "name", Value: "ProductB", Type: parser.RowTypeString}},
			},
		},
		{
			Name: "menus",
			Rows: parser.Rows{
				{{Name: "id", Value: "1", Type: parser.RowTypeString}, {Name: "name", Value: "MenusA", Type: parser.RowTypeString}},
			},
		},
	}

	tests := []struct {
		name               string
		targetSchemaTables []entity.SchemaTable
		want               string
	}{
		{
			name: "without id_type",
			targetSchemaTables: []entity.SchemaTable{
				{Name: "products", Key: "name", Value: "id"},
				{Name: "menus", Key: "name", Value: "id"},
			},
			want: `{"openapi":"3.0.0","info":{"title":"Code generated by github.com/flum1025/sql-enum-generator, DO NOT EDIT.","version":""},"paths":{},"components":{"schemas":{"menus":{"enum":["1"],"type":"string","x-enum-varnames":["MenusA"]},"products":{"enum":["1","2"],"type":"integer","x-enum-varnames":["ProductA","ProductB"]}}}}`,
		},
		{
			name: "with id_type",
			targetSchemaTables: []entity.SchemaTable{
				{Name: "products", Key: "name", Value: "id", IDType: "ProductID"},
				{Name: "menus", Key: "name", Value: "id"},
			},
			want: `{"openapi":"3.0.0","info":{"title":"Code generated by github.com/flum1025/sql-enum-generator, DO NOT EDIT.","version":""},"paths":{},"components":{"schemas":{"menus":{"enum":["1"],"type":"string","x-enum-varnames":["MenusA"]},"products":{"enum":["1","2"],"type":"integer","x-enum-varnames":["ProductA","ProductB"],"x-id-type":"ProductID"}}}}`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			outputPath := filepath.Join(t.TempDir(), "openapi.generated.json")

			if err := NewOpenAPIWriter(tt.targetSchemaTables, outputPath).Write(tables); err != nil {
				t.Fatalf("Write() error = %v", err)
			}

			got, err := os.ReadFile(outputPath)
			if err != nil {
				t.Fatalf("read output: %v", err)
			}

			if string(got) != tt.want {
				t.Errorf("Write() output =\n%s\nwant\n%s", got, tt.want)
			}
		})
	}
}
